job('SimpleWeb-Via-DSL') {
    description("Simple Web project generated by the DSL on ${new Date()}, hosted to github")
    scm {
        git("https://github.com/gtimalsena/DevOps.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven/simple_WebApp/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}